/**
 * Legal `operationOption` range per ride type (#50).
 *
 * The game accepts a value only inside the ride TYPE's static
 * `RideTypeDescriptor.OperatingSettings {MinValue, MaxValue}`
 * (RideSetSettingAction.cpp:274-285), and every refused value, including a
 * `queryAction`, writes an ERROR line to the game log. The plugin API does not expose
 * the range, so the ops controller used to find it by probing: 34-84 refusals per park
 * per 60 days in the #49 matrix. This table removes the need to probe.
 *
 * Generated by `node tools/gen-op-ranges.mjs` from gamesrc at 6fb525e906. Index is the
 * numeric ride type. `null` is a dummy slot (29, 31, 34...) or a type whose
 * OperatingSettings is left at its default {0, 0}, i.e. it has nothing to tune.
 *
 * The "unlock operating limits" cheat widens the real range to 0-255; the API cannot
 * see it, so with the cheat on the controller simply stays inside the normal range.
 */
const RANGES: ([number, number] | null)[] = [[10,27],[7,27],[10,27],[7,27],[5,18],[5,27],[5,27],[5,18],[5,18],[5,18],[5,18],[5,18],[10,40],[7,27],[5,27],[10,27],[5,27],[7,27],[1,4],[10,27],[1,64],[1,5],[1,10],[5,27],[5,27],[20,180],[7,25],[7,15],null,null,null,null,null,[4,25],null,null,[4,4],[1,3],null,null,null,null,[7,30],[5,27],[10,27],null,[3,6],null,[8,8],null,[5,18],[10,27],[7,27],null,[5,18],[10,27],[10,27],[10,27],[10,27],[5,18],[5,27],[5,18],[10,27],[5,27],[10,27],[5,18],[10,27],null,[10,27],null,[20,180],null,[5,18],[7,27],[5,18],[30,50],[5,18],[7,15],null,[5,27],null,[10,20],null,null,null,null,[10,33],[5,27],[7,27],null,[10,31],[10,27],[7,27],[5,18],[7,27],[7,27],[2,10],[7,27]];

/** Whether this ride type appears in the table at all (false = unknown, e.g. a newer game). */
export function isKnownRideType(rideType: number): boolean {
    return rideType >= 0 && rideType < RANGES.length;
}

/** [min, max] for a known type with a tunable range, else null. */
export function operationRange(rideType: number): [number, number] | null {
    if (!isKnownRideType(rideType)) return null;
    const r = RANGES[rideType];
    return r !== null && r[1] > 0 ? r : null;
}
